---
layout: single
title:  "예외 처리"
folder: "java"
categories:
  - java
permalink: categories/java/java003
tags: JAVA
toc: true
toc_sticky: true
sidebar_main: true
published: true
---

## 예외 처리
JAVA에서 예외는 <span style="color: rgb(3, 150, 150); font-weight: bold;">`체크(Check)`</span>와 <span style="color: rgb(3, 150, 150); font-weight: bold;">`언체크(Uncheck)`</span> 예외로 나뉩니다. 체크 예외는 프로그램 내에서 반드시 처리를 해야 하며, 그렇지 않으면 컴파일 오류가 발생합니다. 반면에 언체크 예외는 처리 의무가 없습니다.

예외 또한 객체이며 <span style="color: rgb(3, 150, 150); font-weight: bold;">`Exception`</span> 클래스를 상속받아 생성할 수 있습니다. 생성된 예외는 <span style="color: rgb(3, 150, 150); font-weight: bold;">`throw`</span>를 통해 발생시킬 수 있습니다.

코드 실행 중 예외가 발생했다면 <span style="color: rgb(3, 150, 150); font-weight: bold;">`try-catch`</span> 구문을 활용해 오류를 잡거나 <span style="color: rgb(3, 150, 150); font-weight: bold;">`throws`</span>를 통해 현재 메서드를 호출한 상위 메서드로 넘겨 해결해야 합니다.

try 블록은 예외가 발생할 수 있는 로직을 포함하며, catch 블록에서 예외를 처리합니다. catch는 위에서부터 순서대로 진행되기 때문에 **세부적인 예외 처리를 우선적으로 작성**해야 합니다. finally 블록은 예외 해결 여부와 관계없이 무조건 실행됩니다.

모든 오류를 전부 알고 대응하는 것은 불가능한 일입니다. 반드시 처리해야 하는 중요한 예외만 우선적으로 잡고, 나머지는 모든 예외의 부모 클래스인 Exception으로 묶어서 해결하는 편이 합리적입니다.

## try-with-resource
외부 자원을 사용한 후에는 반드시 연결을 해제해야 하며, 무조건 실행되는 finally 블록을 사용해 자원을 반환하는 방법을 떠올릴 수 있습니다. 하지만 JAVA는 문법적으로 finally 블록을 놓치더라도 컴파일 오류가 발생하지 않기 때문에 연결 해제가 누락될 가능성이 있습니다.

JAVA 7부터 try 블록 내에 사용된 자원이 외부 자원임을 알리고 try가 끝나는 시점에 자동으로 자원 연결을 해제하는 <span style="color: rgb(3, 150, 150); font-weight: bold;">`try-with-resource`</span> 기능이 도입되었습니다. try 블록에 인자(Argument)로 전달되는 클래스는 반드시 <span style="color: rgb(3, 150, 150); font-weight: bold;">`AutoCloseable`</span> 인터페이스를 구현해 <span style="color: rgb(3, 150, 150); font-weight: bold;">`close()`</span> 메서드를 재정의해야 합니다.

생성된 인스턴스를 활용한 블록이 끝나면 자동으로 재정의된 close()를 호출하여 사용한 외부 자원을 반환합니다.

```java
//try-catch-finally
NetworkClientV1 client = new NetworkClientV1(address);

client.initError(data);

try {
	client.connect();
	client.send(data);
}
catch (ConnectException e) {
	System.out.println("[연결 오류] 주소: " + e.getAddress() +
	", 메세지: " + e.getMessage());
}
catch (NetworkClientException e) {
	System.out.println("[네트워크 전송 오류] 메세지: " + e.getMessage());
}
catch (Exception e) {
	System.out.println("[알 수 없는 오류] 메세지: " + e.getMessage());
}
finally {
	client.disconnect();
}
```
```java
//try-with-resource
try (NetworkClientV2 client = new NetworkClientV2(address)) {
	client.initError(data);

	client.connect();
	client.send(data);
	//client.close(); //재정의된 AutoCloseable.close()가 자동으로 호출됨
}
catch (ConnectException e) {
	System.out.println("[연결 오류] 주소: " + e.getAddress() +
	", 메세지: " + e.getMessage());
}
catch (NetworkClientException e) {
	System.out.println("[네트워크 전송 오류] 메세지: " + e.getMessage());
}
catch (Exception e) {
	System.out.println("[알 수 없는 오류] 메세지: " + e.getMessage());
}
```
```java
public class NetworkClientV2 implements AutoCloseable {
@Override
    public void close() throws Exception {
        //...
    }
}
```
```java
public interface AutoCloseable {
    void close() throws Exception;
}
```