---
layout: single
title:  "예외 처리"
folder: "java"
categories:
  - java
permalink: categories/java/java003
tags: JAVA
toc: true
toc_sticky: true
sidebar_main: true
published: true
---

## 예외 분류
Java에서 예외는 체크(Check)와 언체크(Uncheck, Runtime) 예외로 나뉜다. 체크 예외는 프로그램 내에서 반드시 처리를 해야 하며, 그렇지 않으면 컴파일 오류가 발생한다. 파일 입출력, 네트워크, DB 연결 등에서 발생하기 때문에 예측 가능한 예외이고 호출한 쪽에서 복구할 수 있는 가능성이 있다고 가정하기 때문이다.

반면에 언체크 예외는 처리 의무가 없다. 런타임 도중 프로그래밍 오류로 발생하는 오류이기 때문에 사실상 호출자 선에서 처리가 불가능하다. 잘못된 인자 전달, null 접근 등 프로그래밍 오류(논리적 버그)에 의해 발생한다.

예외 또한 객체이며, Exception 클래스를 상속받아 생성할 수 있다. 생성된 예외는 throw를 통해 발생시킬 수 있다. Exception의 하위 클래스인 RuntimeException과 그 자식들을 언체크 예외, 나머지는 체크 예외로 구분한다.

코드 실행 중 예외가 발생했다면 try-catch-finally 구문을 활용해 오류를 잡거나 throws를 통해 상위 클래스로 넘겨 해결해야 한다.

try-catch-finally에서 try 블록은 예외가 발생할 수 있는 로직을 포함하며, catch 블록에서 예외를 처리한다. catch 블록은 위에서부터 순서대로 진행되기 때문에 세부적인 예외 처리를 우선적으로 작성해야 한다. 마지막으로 finally 블록은 예외 해결 여부와 관계없이 무조건 실행된다.

모든 오류를 전부 알고 대응하는 것은 불가능하다. 따라서 반드시 처리해야 하는 중요한 예외만 우선적으로 잡고, 나머지는 모든 예외의 부모 클래스인 Exception으로 묶어서 해결한 후, 로그 기록을 통해 문제를 해결하는 편이 일반적이다.

## try-with-resources
외부 자원을 사용한 후에는 반드시 연결을 해제해야 하며, 반드시 실행되는 finally 블록을 사용해 자원을 반환하는 방법을 떠올릴 수 있다. 하지만 Java는 문법적으로 finally 블록을 놓치더라도 컴파일 오류가 발생하지 않기 때문에 연결 해제가 누락될 가능성이 있다.

Java 7부터 try 블록 내에 사용된 자원이 외부 자원임을 알리고 try가 끝나는 시점에 자동으로 자원 연결을 해제하는 try-with-resources 기능이 도입되었다. try 블록에 인자(Argument)로 전달되는 클래스는 반드시 AutoCloseable 인터페이스를 구현해 close() 메서드를 재정의해야 한다.

try-with-resources 기능은 생성된 인스턴스를 활용한 블록이 끝나면 앞서 재정의된 close()를 자동으로 호출하여 사용했던 외부 자원을 반환한다.

```java
//try-catch-finally
NetworkClient client = new NetworkClient(address);

try {
	client.initError(data);
	client.connect();
	client.send(data);
}
catch (ConnectException e) {
	System.out.println("[연결 오류] 주소: " + e.getAddress() +
	", 메세지: " + e.getMessage());
}
catch (NetworkClientException e) {
	System.out.println("[네트워크 전송 오류] 메세지: " + e.getMessage());
}
catch (Exception e) {
	System.out.println("[알 수 없는 오류] 메세지: " + e.getMessage());
}
finally {
	client.disconnect();
}
```
```java
//try-with-resources
try (NetworkClient client = new NetworkClient(address)) {
	client.initError(data);
	client.connect();
	client.send(data);
	//client.close(); //자동 호출
}
catch (ConnectException e) {
	System.out.println("[연결 오류] 주소: " + e.getAddress() +
	", 메세지: " + e.getMessage());
}
catch (NetworkClientException e) {
	System.out.println("[네트워크 전송 오류] 메세지: " + e.getMessage());
}
catch (Exception e) {
	System.out.println("[알 수 없는 오류] 메세지: " + e.getMessage());
}
```
```java
public class NetworkClient implements AutoCloseable {
	//... initError, connect (throw ConnectException), 
	//send(throw NetworkClientException)

    @Override
    public void close() throws Exception {
        //...
    }
}
```
```java
public interface AutoCloseable {
    void close() throws Exception;
}
```